In [1]:
import keras


Using TensorFlow backend.


In [2]:
import numpy as np

In [3]:
data_in = np.array([[1, 1],
         [1, 0],
         [0, 1],
         [0, 0]])

In [4]:
print(data_in)

[[1 1]
 [1 0]
 [0 1]
 [0 0]]


In [6]:
logic_and = np.array([[1],
                    [0],
                    [0],
                    [0]])
print(logic_and)

[[1]
 [0]
 [0]
 [0]]


In [26]:
logic_or = np.array([[1],
                    [1],
                    [1],
                    [0]])
print(logic_or)

[[1]
 [1]
 [1]
 [0]]


In [27]:
logic_xor = np.array([[0],
                    [1],
                    [1],
                    [0]])
print(logic_xor)

[[0]
 [1]
 [1]
 [0]]


In [41]:
model = keras.models.Sequential(layers = [keras.layers.Dense(input_dim=2,units = 2),
                                          keras.layers.Activation(keras.activations.sigmoid),
                                          keras.layers.Dense(units = 1),
                                          keras.layers.Activation(keras.activations.sigmoid)])
model.compile(optimizer=keras.optimizers.SGD(lr = 0.5), loss='mse')

In [42]:
model.weights


[<tf.Variable 'dense_5/kernel:0' shape=(2, 2) dtype=float32_ref>,
 <tf.Variable 'dense_5/bias:0' shape=(2,) dtype=float32_ref>,
 <tf.Variable 'dense_6/kernel:0' shape=(2, 1) dtype=float32_ref>,
 <tf.Variable 'dense_6/bias:0' shape=(1,) dtype=float32_ref>]

In [43]:
keras.backend.eval(model.weights[0])

array([[ 0.60074174,  0.71169865],
       [-0.12169945,  0.70969296]], dtype=float32)

In [54]:
model.fit(data_in, logic_xor, epochs =2000, verbose = False)


In [58]:
model.predict(np.array([[0,1]]))

array([[ 0.97663569]], dtype=float32)